### ISSUE TITLE
Add error preventions when changing variable from character to factor automatically

### ISSUE THREAD

**Issue by boyiguo1** [bcjaeger/tibbleOne#2]
Header creation will be a problem when empty string ("") exists in the variable that is used as either _strata_ or _by_ variable. 

As tibble_one automatically changed variables from character (variable type) to factor(variable type), it coded the missing level as a level,“”(empty string). further, when it created strata, it assigned “random” names to this missing level, which were “V_X” and “V_Y” multiple times.

Suggested solution:
1. Examine if "" exists in the variable 
2. If yes, 
a) report error/warning
b) replace with "Missing Level" or remove from dataset.

**Comment by bcjaeger** [comment]
Great idea. Just added a checking function to tibble_one for this. 

``` r
library(tibbleOne, warn.conflicts = F)

df <- data.frame(
  A = c(1,2,3),
  B = factor(c("One", "", "Three"), levels = c("One", "", "Three")),
  C = factor(c("One", "Two", " "), levels = c("One", "Two", " "))
)

tibble_one(df, formula =  ~ B | C)
#> Error: factors in data contain blank levels: B and C.
#> Blank levels can cause errors in tabulation functions.
```

<sup>Created on 2020-03-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by boyiguo1** [comment]
I think this is very efficient.
